export const mockDataForUT = {
  id: 'walnut-led-desk-lamp-w4013',
  name: 'Walnut LED Desk Lamp',
  links: {
    www: 'https://www.westelm.com/products/walnut-led-desk-lamp-w4013/',
  },
  price: {
    regular: 159,
    selling: 159
  },
  thumbnail: {
    size: 'm',
    meta: '',
    alt: '',
    rel: 'thumbnail',
    width: 363,
    href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-6-m.jpg',
    height: 363,
  },
  hero: {
    size: 'm',
    meta: '',
    alt: '',
    rel: 'hero',
    width: 363,
    href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-6-m.jpg',
    height: 363,
  },
  images: [{
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-2-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-5-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-3-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-7-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-1-m.jpg',
      height: 363,
    },
    {
      size: 'm',
      meta: '',
      alt: '',
      rel: 'althero',
      width: 363,
      href: 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202111/0061/walnut-led-desk-lamp-4-m.jpg',
      height: 363,
    },
  ],
  swatches: [],
  messages: [],
  flags: [{
    bopisSuppress: false,
    rank: 3,
    id: 'newcore'
  }],
  reviews: {
    recommendationCount: 0,
    likelihood: 0,
    reviewCount: 0,
    averageRating: 0,
    id: 'walnut-led-desk-lamp-w4013',
    type: 'GROUP_REVIEWS',
  },
};
